language: dart

dart:
  - 2.4.0
  - dev

dart_task:
  - test: -p vm
    xvfb: false
  - test: -p firefox
  - dartanalyzer: --fatal-warnings --fatal-infos .

matrix:
  include:
  - dart: dev
    dart_task: dartfmt

# Only building master means that we don't run two builds for each pull request.
branches:
  only: [master]

cache:
  directories:
    - $HOME/.pub-cache
