name: yaml
version: 3.1.1-dev

description: A parser for YAML, a human-friendly data serialization standard
homepage: https://github.com/dart-lang/yaml

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  collection: ^1.15.0
  source_span: ^1.8.0
  string_scanner: ^1.1.0

dev_dependencies:
  lints: ^1.0.0
  path: ^1.8.0
  test: ^1.16.0
